ec2:
  ami_id: ami-0866a3c8686eaeeba
  availability_zone: us-east-1a
  instance_type: g4dn.xlarge
  key_pair_name: stranger-things-key-dct
  max_spot_price: 0.5
  region: us-east-1
  security_group_ids: []
  subnet_id: ""
  use_spot_instances: false
  volume_size: 100
  volume_type: gp3
gradio:
  enable_auth: true
  enable_ssl: false
  host: 0.0.0.0
  max_file_size: 50
  port: 7860
  ssl_cert_path: ""
  ssl_key_path: ""
s3:
  bucket_name: stranger-things-nlp-duongcongthuyet
  checkpoints_prefix: checkpoints/
  logs_prefix: logs/
  model_prefix: models/
  region: us-east-1
  results_prefix: results/
  training_data_prefix: data/training/
training:
  base_model_llama: meta-llama/Llama-3.2-3B-Instruct
  base_model_qwen: Qwen/Qwen2.5-3B-Instruct
  batch_size: 1
  fp16: true
  gradient_accumulation_steps: 4
  gradient_checkpointing: true
  learning_rate: 0.0002
  lora_alpha: 16
  lora_dropout: 0.1
  lora_r: 64
  max_steps: 1000
  num_epochs: 3
